[build]
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/paiement"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "no-store"

[[headers]]
  for = "/paiement/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "no-store"

[[headers]]
  for = "/merci"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "no-store"

[[headers]]
  for = "/merci/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive"
    Cache-Control = "no-store"
